apiVersion: v1
kind: Service
metadata:
  name: prod-iterview-graphql-service
  namespace: iterview-prod
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 80
  selector:
    server: prod-iterview-graphql